[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[lib]
name = "manager"
bench = false

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
clap = { version = "4.5.20", features = ["derive"] }
tempfile = "3.13.0"
